---

version: "2"
services:
  redis:
    build: .
    volumes:
      - /opt/gopher/redis.conf:/etc/redis/redis.conf:ro
      - /opt/gopher/security.conf:/etc/redis/security.conf:ro
      - /opt/gopher/data:/var/lib/redis
    ports:
      - "70:6379"
    user: redis
